[Fish-15] confusion matrix for metric
boostcampaitech4lv23cv2/final-project-level3-cv-13 pull request #30
Opened 2023-01-27 07:18 UTC by lsvv1217

confusion matrix 만들어서 wandb에서 시각화 할 수 있게 구현했습니다

2023-01-27 09:14 UTC, 0seob approved these changes
f1 score logging이 가능하도록 train.py 변경 부탁드립니다.

2023-01-27 09:15 UTC, 0seob requested changes
f1 score logging이 가능하도록 train.py 변경 부탁드립니다.

2023-01-30 02:09 UTC, lsvv1217 commented
f1 score logging으로 수정했습니다

2023-01-30 05:39 UTC, LimePencil approved these changes
visualization 보기 좋네요!

2023-01-30 05:39 UTC, SangJunni approved these changes
Confusion matrix 시각화 수고하셨습니다!

2023-01-30 05:45 UTC, 0seob approved these changes
f1 score로 metric 변경 수고하셨습니다!!

2023-01-30 05:59 UTC, merged